Repository GDSC-Lodz-University-of-Technology/warzywniax, pull requests merged in 2023-03, with the labels that each got.

#8 chore(workflow): setup project
  .eslintignore
  .eslintrc.json
  .gitattributes
  .gitignore
  .prettierignore
  .prettierrc.json
  git-hooks/pre-commit
  git-hooks/prepare-commit-msg
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/configs/firebase.config.ts
  src/configs/mui.config.ts
  src/index.css
  src/locales/en/offers.json
  src/locales/en/shops.json
  src/locales/i18n.ts
  src/locales/pl/offers.json
  src/locales/pl/shops.json
  src/main.tsx
  src/pages/OffersPage/OffersPage.tsx
  src/pages/ShopsPage/ShopsPage.tsx
  src/router/offers.route.tsx
  src/router/router.tsx
  src/router/shops.route.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: workflow

#20 chore(firebase): set-up firebase connection and emulators
  .env
  .env.development
  .env.production
  .gitignore
  firebase/.firebaserc
  firebase/firebase.json
  firebase/firestore.indexes.json
  firebase/firestore.rules
  firebase/storage.rules
  package-lock.json
  package.json
  src/common/utils/connectToFirebaseEmulators.ts
  src/common/utils/zod.utils.ts
  src/configs/firebase.config.ts
  src/main.tsx
  src/services/FirebaseService/OffersCollection/OffersCollection.types.ts
  src/services/FirebaseService/ShopsCollection/LocationCollection.types.ts
  src/services/FirebaseService/ShopsCollection/ProductCollection.types.ts
  src/services/FirebaseService/ShopsCollection/ShopsCollection.types.ts
  src/services/FirebaseService/UsersCollection/UsersCollection.types.ts
  src/services/FirebaseService/firebase.config.ts
  src/vite-env.d.ts
Labels: feature, workflow

#23 chore(geneators): add fake data and fake data generator
  .eslintrc.json
  custom-types/firestore-custom-types.d.ts
  custom-types/vite-env.d.ts
  firebase/seed/auth_export/accounts.json
  firebase/seed/auth_export/config.json
  firebase/seed/firebase-export-metadata.json
  firebase/seed/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/seed/firestore_export/all_namespaces/all_kinds/output-0
  firebase/seed/firestore_export/firestore_export.overall_export_metadata
  firebase/seed/storage_export/buckets.json
  mockDataGenerator/generateMockData.ts
  mockDataGenerator/generateOffersMock.ts
  mockDataGenerator/generateRandomData.utils.ts
  mockDataGenerator/generateShopsMock.ts
  package-lock.json
  package.json
  src/common/utils/generateRandomInteger.ts
  src/common/utils/generateRandomNumber.ts
  src/common/utils/getLastArrayIdx.ts
  src/common/utils/isEmptyArray.ts
  src/common/utils/isNullOrUndefined.ts
  src/errors/DocumentDoesntExistsError.ts
  src/services/FirebaseService/FireBaseService.types.ts
  src/services/FirebaseService/OffersCollection/OffersCollection.types.ts
  src/services/FirebaseService/OffersCollection/OffersCollectionService.ts
  src/services/FirebaseService/ShopsCollection/LocationService.ts
  src/services/FirebaseService/ShopsCollection/ProductsService.ts
  src/services/FirebaseService/ShopsCollection/ShopsService.ts
  src/services/FirebaseService/UsersCollection/UsersCollection.types.ts
  tsconfig.json
Labels: workflow

#28 feat(queries): add custom queries functions to fetch collections data
  custom-types/firestore-custom-types.d.ts
  mockDataGenerator/generateOffersMock.ts
  src/common/types.ts
  src/common/utils/unwrapQuerySnapshot.ts
  src/services/FirebaseService/OffersCollection/OffersCollectionService.ts
  src/services/FirebaseService/ShopsCollection/LocationService.ts
  src/services/FirebaseService/ShopsCollection/ProductsService.ts
  src/services/FirebaseService/ShopsCollection/ShopsService.ts
Labels: feature

#33 fix(fake-data): add shop owner id to every offer record
  firebase/seed/auth_export/accounts.json
  firebase/seed/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/seed/firestore_export/all_namespaces/all_kinds/output-0
  firebase/seed/firestore_export/firestore_export.overall_export_metadata
  mockDataGenerator/generateOffersMock.ts
  src/services/FirebaseService/OffersCollection/OffersCollection.types.ts
Labels: bug

#32 fix(fake-data): add shop owner id to every shop record
  firebase/seed/auth_export/accounts.json
  firebase/seed/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/seed/firestore_export/all_namespaces/all_kinds/output-0
  firebase/seed/firestore_export/firestore_export.overall_export_metadata
  mockDataGenerator/generateMockData.ts
  mockDataGenerator/generateOffersMock.ts
  mockDataGenerator/generateShopsMock.ts
  mockDataGenerator/generateUsersMock.ts
  src/errors/AuthError.ts
  src/errors/ShouldNeverHappenError.ts
  src/services/FirebaseService/AuthService/AuthService.ts
  src/services/FirebaseService/AuthService/AuthService.types.ts
  src/services/FirebaseService/OffersCollection/OffersCollection.types.ts
  src/services/FirebaseService/ShopsCollection/ShopsCollection.types.ts
Labels: bug

#34 feat(firebase): add security rules
  firebase/firestore.rules
Labels: feature

#26 feature(offer page): create mobile & desktop offer components
  firebase/seed/auth_export/accounts.json
  firebase/seed/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase/seed/firestore_export/all_namespaces/all_kinds/output-0
  firebase/seed/firestore_export/firestore_export.overall_export_metadata
  mockDataGenerator/generateOffersMock.ts
  public/offerPageWaves.svg
  src/common/utils/connectToFirebaseEmulators.ts
  src/common/utils/translateCategory.ts
  src/components/Button/Button.styled.ts
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/locales/en/navbar.json
  src/locales/en/offers.json
  src/locales/en/products-categories.json
  src/locales/i18n.ts
  src/locales/pl/navbar.json
  src/locales/pl/offers.json
  src/locales/pl/products-categories.json
  src/main.tsx
  src/mui/mui.config.ts
  src/pages/OffersPage/OffersPage.tsx
  src/pages/OffersPage/components/LocationMark/Location.types.ts
  src/pages/OffersPage/components/LocationMark/LocationMark.styled.ts
  src/pages/OffersPage/components/LocationMark/LocationMark.tsx
  src/pages/OffersPage/components/Offer/Offer.tsx
  src/pages/OffersPage/components/Offer/Offer.types.ts
  src/pages/OffersPage/components/OfferList/OfferList.tsx
  src/pages/OffersPage/components/OfferMap/OfferMap.tsx
  src/pages/OffersPage/components/OfferTags/OfferTags.styled.ts
  src/pages/OffersPage/components/OfferTags/OfferTags.tsx
  src/pages/OffersPage/components/OfferTags/OfferTgas.types.ts
  src/pages/OffersPage/components/ViewSwitch/ViewSwitch.styled.ts
  src/pages/OffersPage/components/ViewSwitch/ViewSwitch.tsx
  src/pages/OffersPage/components/ViewSwitch/ViewSwitch.types.ts
  src/services/FirebaseService/OffersCollection/OffersCollection.types.ts
  src/templates/NavBar/NavBar.styled.ts
  src/templates/NavBar/NavBar.tsx
Labels: feature

#38 feat(auth): create login and register pages
  package-lock.json
  package.json
  public/google_icon.svg
  src/App.tsx
  src/components/Button/Button.styled.ts
  src/components/Form/FormErrorMessage/FormError.styled.ts
  src/components/Form/FormErrorMessage/FormErrorMessage.tsx
  src/components/Form/FormInput/FormInput.tsx
  src/components/Form/FormInput/FormInput.types.ts
  src/components/Loader/FullScreenLoader/FullScreenLoader.tsx
  src/locales/en/auth.json
  src/locales/en/forms.json
  src/locales/i18n.ts
  src/locales/pl/auth.json
  src/locales/pl/forms.json
  src/pages/AuthPage/LoginPage/LoginPage.tsx
  src/pages/AuthPage/LoginPage/components/LoginForm.tsx
  src/pages/AuthPage/LoginPage/components/LoginForm.types.ts
  src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  src/pages/AuthPage/RegisterPage/components/RegisterForm.tsx
  src/pages/AuthPage/RegisterPage/components/RegisterForm.types.ts
  src/pages/OffersPage/components/OfferTags/OfferTags.tsx
  src/router/auth.route.tsx
  src/router/router.tsx
  src/templates/BaseLayout/BaseLayout.styled.ts
  src/templates/BaseLayout/BaseLayout.tsx
  vite.config.ts
Labels: feature
