Repository GDSC-Lodz-University-of-Technology/warzywniax, pull requests merged in 2023-04, with the labels that each got.

#44 refactor(auth): Improve auth pages structure
  public/facebook_icon.svg
  public/twitter_icon.svg
  src/components/Button/Button.styled.ts
  src/locales/en/auth.json
  src/locales/pl/auth.json
  src/pages/AuthPage/LoginPage/LoginPage.tsx
  src/pages/AuthPage/LoginPage/components/LoginForm.tsx
  src/pages/AuthPage/LoginPage/components/LoginForm/LoginForm.tsx
  src/pages/AuthPage/LoginPage/components/LoginForm/LoginForm.types.ts
  src/pages/AuthPage/LoginPage/components/SignInProvidersBox/SignInProvidersBox.tsx
  src/pages/AuthPage/LoginPage/components/SignInProvidersBox/SignInProvidersBox.types.ts
  src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  src/pages/AuthPage/RegisterPage/components/RegisterForm.tsx
  src/pages/AuthPage/RegisterPage/components/RegisterForm/RegisterForm.tsx
  src/pages/AuthPage/RegisterPage/components/RegisterForm/RegisterForm.types.ts
  src/pages/AuthPage/components/AuthFormWrapper/AuthFormWrapper.styled.ts
  src/pages/AuthPage/components/AuthFormWrapper/AuthFormWrapper.types.ts
  src/pages/AuthPage/components/AuthFormWrapper/AuthFormWrappper.tsx
Labels: refactor, improvemnt

#37 featurea(dashboard): create vendor dashboard
  firebase/firestore.rules
  src/App.tsx
  src/locales/en/dashboard.json
  src/locales/en/shops.json
  src/locales/i18n.ts
  src/locales/pl/dashboard.json
  src/locales/pl/shops.json
  src/pages/NewShopPage/NewShopPage.tsx
  src/pages/NewShopPage/components/CreateShopForm/CreateShopForm.tsx
  src/pages/NewShopPage/components/CreateShopForm/CreateShopForm.types.tsx
  src/pages/VendorDashboard/VendorDashboard.tsx
  src/pages/VendorDashboard/components/DashboardPanel/DashboardPanel.tsx
  src/pages/VendorDashboard/components/DashboardPanel/DashboardPanel.types.ts
  src/pages/VendorDashboard/components/UserShopInfo/UserShopInfo.tsx
  src/pages/VendorDashboard/components/UserShopInfo/UserShopInfo.types.tsx
  src/pages/VendorDashboard/components/UserShopsPanel/UserShopsPanel.tsx
  src/pages/VendorDashboard/components/UserShopsPanel/UserShopsPanel.types.tsx
  src/router/router.tsx
  src/router/shops.route.tsx
  src/router/vendorDashboard.route.tsx
  src/services/FirebaseService/AuthService/AuthService.ts
  src/services/FirebaseService/ShopsCollection/ShopsService.ts
Labels: feature, shop

#50 doc(readme): add README with the most essential information
  README.md
  package.json
Labels: documentation
